#!/bin/bash

# The serial number is written in following format
# -------0x00 0x01 0x02 0x03 0x04 0x05 0x06 0x07 0x08 0x09------
# ------- BA   2C   MSB...........LSB   MSB...........LSB-------
# -------Identifier  Meter serial No.    Checksum (cksum)-------
# -------0x10........................................0x2f-------
# -------		   SHA256SUM of Meter serial No.		 -------
#########	same copy of above data from 0x80	#########


chipAddr=0x54
bus=${I2C_BUS:-1}
RETURN_VALUE=2

function verify {
	echo "verifying the checksum"
	checksum=""
	for l in {6..9}; do getValue="$(i2cget -y $bus $chipAddr "0x0""$l")"; checksum="$checksum""${getValue:2:2}"; done
	getFile=$(cksum /tmp/cksum_temp | awk '{print $1}')
	hex_checksum=$(printf "%08x" $getFile)
	if [[ "$hex_checksum" == "$checksum" ]]; then
		echo "checksum is verified"
		RETURN_VALUE=1
	else
		echo "checksum verification failed"
	fi
	echo "verifying sha key"
	sha256Value=""
	for l in {16..47}; do getValue="$(i2cget -y $bus $chipAddr $l)"; sha256Value="$sha256Value""${getValue:2:2}";done
	read -r shaval < /tmp/sha_temp
	echo "$sha256Value"
	echo "$shaval"
	if [[ "$sha256Value" == "$shaval" ]]; then
		echo "SHA256  verified"
		if [ $RETURN_VALUE -eq 1 ]; then
			RETURN_VALUE=0
		fi	
	else
		echo "sha256 verification failed"
	fi
}

function readFromI2c {
	value=""
	for l in {2..5}; do getValue="$(i2cget -y $bus $chipAddr "0x0""$l")"; value="$value""${getValue:2:2}"; done
	shavalue=""
	for l in {16..47}; do getValue="$(i2cget -y $bus $chipAddr $l)" ; shavalue="$shavalue""${getValue:2:2}"; done
	echo "$shavalue" > /tmp/sha_temp
	echo "the value identified is: $(printf "%d" "0x""$value")"
	echo "$value" > /tmp/cksum_temp
}

identifier=""
for l in {0..1}; do identifier="$identifier""$(i2cget -y $bus $chipAddr "0x0""$l")"; done
if [[ "$identifier" == "0xba0x2c" ]]; then
	echo "identifier is found"
	readFromI2c
	verify
fi
exit $RETURN_VALUE
